.\" Copyright 1999-2001 Michal Suszycki <mt_suszycki@yahoo.com>
.\" Copyright 2018 Paul Wise <pabs3@bonedaddy.net>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"
.TH WHOWATCH 1 "27 Feb 2000"
.SH NAME
whowatch \- console, interactive, process and users monitoring tool.
.SH DESCRIPTION
\fBWhowatch\fR is an console, interactive users and process monitoring
tool.
It displays information about the users currently logged on to the machine, in real-time.
Besides standard information (login name, tty, host, user's process),
the type of the connection (ie. telnet or ssh) is shown.
Display of users command line can be switch to tty idle time.
Certain user can be selected and his processes tree may be viewed as well
as tree of all system processes. Tree may be displayed with additional
column that shows owner of each process.
In the process tree mode SIGINT, SIGHUP, SIGTERM and SIGKILL signals can be sent to the
selected process. Killing processes is just as simple and fun as deleting
lines on the screen.
.PP
.nh
\fBWhowatch\fR has no command line options or configuration file.
All actions are performed in real time by pressing following keys:
.PP
Users list mode:
.PP
.TP
.B 'up' 'down'
cursor movement
.TP
.B 'i'
toggle between user command line and idle time
.TP
.B 'c'
full command line on/off. Disabling full command line can save CPU time.
It can give you also some additional information about process executable.
.TP
.B 'enter'
view selected user's processes tree.
.TP
.B 't'
all system processes (init tree)
.PP
Tree mode:
.TP
.B 'up' 'down'
cursor movement
.TP
.B 'enter'
go back to users list
.TP
.B 'o'
show processes owners
.TP
.B 'c'
full command line on/off. Disabling full command line can save CPU time.
It can give you also some additional information about process executable.
.TP
.B 'Ctrl-I'
send INT signal to selected process
.TP
.B 'Ctrl-K'
send KILL signal to selected process
.TP
.B 'Ctrl-U'
send HUP signal to selected process
.TP
.B 'Ctrl-T'
send TERM signal to selected process

.SH PLUGINS
Whowatch has ability to load plugin during program run.
Plugin prints information inside details window.
Plugins gives flexibility: if some specific information about
process, user or system is needed then separate program could be
written to obtain such information.
Since there are three kinds of deatils window (process, user and
system) maximum three plugins can be loaded.
Whowatch has very simple API to write plugins.



.SH FILES
Program reads \fI/var/log/wtmp\fR, \fI/var/run/utmp\fR. Under Linux program
also reads files from
\fI/proc\fR directory. Without read access to these files \fBwhowatch\fR
funcionality will be limited or program will not even start.

.PD
.SH "SEE ALSO"
.BR finger (1)
.BR ps (1),
.BR pstree (1),
.BR top (1),
.BR w (1),
.BR lsof (8),
.BR kill (1)
.BR killall (1)

.SH "BUGS"
Because lack of ut_pid in utmp and wtmp structures
in *BSD systems, program tries to obtain pid of a login shell by analyzing
processes controlling terminal and processes names. Under some conditions
it may lead to incorrect results ie. there will be incorrect processes
tree associated with user's session.

.SH "AUTHOR"
.nf
Michal Suszycki <mike@wizard.ae.krakow.pl>,
http://wizard.ae.krakow.pl/~mike/
Tree functions written by Jan Bobrowski <jb@wizard.ae.krakow.pl>,
http://wizard.ae.krakow.pl/~jb/
.fi
