.TH WHOWATCH 1 "Aug 14 1999"
.SH NAME
whowatch \- watch logged users in real time
.SH DESCRIPTION
\fBWhowatch\fR is a ncurses who-like utility that displays information 
about the users currently logged on to the machine, in real-time.
Besides standard informations (login name, tty, host, user's process),
the type of the connection (ie. telnet or ssh) is shown.
Display of users command line can be switch to tty idle time.
Certain user can be selected and his processes tree may be viewed as well
as tree of all system processes. Tree may be displayed with additional
column that shows owner of each process.
In the process tree mode SIGINT and SIGKILL signals can be sent to the 
selected process. 
.PP
.nh
\fBWhowatch\fR has no command line options or configuration file. 
All action is performed in real time by pressing following keys:
.PP
Users list mode:
.PP
.nf
up, down - cursor movement
i - toggle between user command line and idle time
enter - view selected user's processes tree.
t - all system processes (init tree)
.PP
Tree mode:
.PP
.nf
up, down - cursor movement
enter - go back to users list
o - show processes owners
Ctrl-I - send INT signal to selected process
Ctrl-K - send KILL signal to selected process

.SH FILES
Program reads \fI/var/log/wtmp\fR, \fI/var/run/utmp\fR and files from
\fI/proc\fR directory. Without read access to these files \fBwhowatch\fR
funcionality will be limited or program will not even start.

.PD
.SH "SEE ALSO"
.BR finger (1)
.BR ps (1),
.BR pstree (1),
.BR top (1),
.BR w (1),

.SH AUTHOR
.nf
Michal Suszycki <mike@wizard.ae.krakow.pl>
Tree functions by Jan Bobrowski<jb@wizard.ae.krakow.pl>
.fi

